### ISSUE TITLE
event on marker click

### ISSUE THREAD

**Issue by pmakowski** [JaWeilBaum/pyqtlet2#18]
Hi, 
thanks for your work.
Is is possible to get information about a marker when user click on it ?
map.clicked.connect is quiet when you click on a marker.

Thanks

**Comment by JaWeilBaum** [comment]
Hi @pmakowski you can connect to the `click` event of a marker. You can find the event inside the marker class. Have a look [here](https://github.com/JaWeilBaum/pyqtlet2/blob/3305c74aaa3898799e8bd600c2fd30477f3bc3f8/pyqtlet2/leaflet/layer/marker/marker.py#L23). 

There is a known limitation, that you will not get updates from a marker when you add them after the application/map was initialized. The limitaion is made by [QWebChannel::registerObject](https://doc-snapshots.qt.io/qt6-dev/qwebchannel.html#registerObject).

My workaround in a project where I have multiple hundred markers is, to add a set of markers in the beginning and managing thier visibility during the application lifecyle.
