### ISSUE TITLE
Is there any way I can include and use Leaflet's plugins?

### ISSUE THREAD

**Issue by maelchiotti** [JaWeilBaum/pyqtlet2#36]
Hi, I would like to display a heatmap but Leafleat doesn't have this functionality natively.

However, a lot of [plugins](https://leafletjs.com/plugins.html#heatmaps) can be used, such as [heatmap.js](https://www.patrick-wied.at/static/heatmapjs/plugin-leaflet-layer.html).

Is there any way I could use `self.map.runJavaScript()` to include such a plugin and use it?

**Comment by JaWeilBaum** [comment]
Hi @maelchiotti , If you still look for this, you might have a look at my PR #17 you could add more plugins like this. I hope this helps.
