### ISSUE TITLE
KeyError: 'options'

### ISSUE THREAD

**Issue by xukegithub** [JaWeilBaum/pyqtlet2#42]
layer.py

```python
 def bindPopup(self, content, options=None):
        js = '{layerName}.bindPopup("{content}"'.format(
                layerName=self._layerName, content=content)
        if options:
            js += ', {options}'.format(self._stringifyForJs(options))
        js += ')'
        self.runJavaScript(js)
        return self

```
when called `marker.bindPopup(' ', {'autoPan': False})` , then throw
    js += ', {options}'.format(self._stringifyForJs(options))
KeyError: 'options'

`js += ', {options}'.format(options=self._stringifyForJs(options))`   is ok

**Comment by JaWeilBaum** [comment]
Hey, thanks for the bug report! Never used the options kwarg there. I'll fix this!

**Comment by xukegithub** [comment]
thanks
